# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(help_text='ex: +6281xxxxxxx', max_length=255, unique=True)),
                ('whatsapp_number', models.CharField(help_text='ex: +6281xxxxxx', max_length=255, unique=True)),
                ('pk_number', models.PositiveSmallIntegerField()),
                ('previous_university', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.SmallIntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('type', models.SmallIntegerField(choices=[(1, 'Volunteer'), (2, 'Initiator')])),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
