# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-22 07:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20170121_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(help_text='ex: +6281xxxxxxx', max_length=255, unique=True, verbose_name='Mobile number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pk_number',
            field=models.PositiveSmallIntegerField(verbose_name='PK number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='previous_university',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Previous university'),
        ),
        migrations.AlterField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(help_text='ex: +6281xxxxxx', max_length=255, unique=True, verbose_name='Whatsapp number'),
        ),
    ]
